version: "3.4"
services:
  webapi:
    tty: true
    build: ./src
    ports:
      - "7666:80"
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - web-variables.env

  db:
    networks:
      - app-network
    build: ./db

networks:
  app-network:
    driver: bridge
