CREATE TABLE db_user.USUARIOS (
  IdUsuario    INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  Email     VARCHAR(30) NOT NULL,
  Senha     CHAR(64) NOT NULL,
  Nome      VARCHAR(50) NOT NULL,
  Nascimento DATE,
  DtInsercao DATETIME,
  DtAtualizacao DATETIME
) Engine = InnoDB;


CREATE UNIQUE INDEX UNIQUE_EMAIL_USUARIO ON USUARIOS(Email);
CREATE INDEX IDX_EMAIL_SENHA ON USUARIOS(Email, Senha);

CREATE TABLE db_user.TOKENS (
  IdToken INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  IdUsuario INT NOT NULL,
  Token CHAR(32) NOT NULL,
  DtInsercao DATETIME,
  DtExpiracao DATETIME,
  INDEX (IdUsuario),
  FOREIGN KEY(IdUsuario) REFERENCES USUARIOS(IdUsuario) ON DELETE CASCADE ON UPDATE CASCADE
) Engine = InnoDB;

CREATE UNIQUE INDEX UNIQUE_TOKEN_TOKENS ON TOKENS(Token);