CREATE TABLE db_user.USUARIOS (
  IdUsuario    INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  Email     VARCHAR(30) NOT NULL,
  Senha     CHAR(64) NOT NULL,
  Nome      VARCHAR(50) NOT NULL,
  Nascimento DATE,
  DtInsercao DATETIME,
  DtAtualizacao DATETIME
) Engine = InnoDB;


CREATE UNIQUE INDEX UNIQUE_EMAIL_USUARIO ON USUARIOS(Email);
CREATE INDEX IDX_EMAIL_SENHA ON USUARIOS(Email, Senha);